package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

type appRouteStatus struct {
	Path      string `json:"path"`
	VPN       int    `json:"vpn"`
	Direct    int    `json:"direct"`
	Managed   int    `json:"managed"`
	Unmanaged int    `json:"unmanaged"`
}
type routeSnapshot struct {
	SystemDevice    string              `json:"systemDevice,omitempty"`
	RemoteNetworks  []string            `json:"remoteNetworks,omitempty"`
	State           string              `json:"state"`
	Message         string              `json:"message,omitempty"`
	Device          string              `json:"device,omitempty"`
	UpdatedAt       int64               `json:"updatedAt"`
	VPN             int                 `json:"vpn"`
	Direct          int                 `json:"direct"`
	Blocked         int                 `json:"blocked"`
	Unknown         int                 `json:"unknown"`
	VPNObserved     bool                `json:"vpnObserved"`
	Apps            []appRouteStatus    `json:"apps"`
	CaptureMode     string              `json:"captureMode,omitempty"`
	OriginalRoute   bool                `json:"originalRoute"`
	CommandResult   *routeCommandResult `json:"commandResult,omitempty"`
	RoutingMode     string              `json:"routingMode,omitempty"`
	TailscaleActive bool                `json:"tailscaleActive"`
	TailscaleRoutes int                 `json:"tailscaleRoutes"`
}
type coreConnections struct {
	Connections []struct {
		ID       string `json:"id"`
		Metadata struct {
			ProcessPath string `json:"processPath"`
		} `json:"metadata"`
		Chains []string `json:"chains"`
	} `json:"connections"`
}

func coreSnapshot(client *http.Client, port uint16, token string) (coreConnections, error) {
	request, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/connections", port), nil)
	request.Header.Set("Authorization", "Bearer "+token)
	response, err := client.Do(request)
	if err != nil {
		return coreConnections{}, err
	}
	defer response.Body.Close()
	if response.StatusCode != 200 {
		return coreConnections{}, errors.New("controller unavailable")
	}
	var result coreConnections
	err = json.NewDecoder(io.LimitReader(response.Body, 4<<20)).Decode(&result)
	return result, err
}

// Keep only application attribution and counts, never destination addresses/URLs.
func summarizeConnections(core coreConnections, paths []string, previous routeSnapshot) routeSnapshot {
	previous.VPN = 0
	previous.Direct = 0
	previous.Blocked = 0
	previous.Unknown = 0
	previous.Apps = make([]appRouteStatus, len(paths))
	for i, path := range paths {
		previous.Apps[i].Path = path
	}
	for _, connection := range core.Connections {
		throughVPN, direct := false, false
		for _, chain := range connection.Chains {
			if chain == "GoConnect" {
				throughVPN = true
			}
			if isDirectChain(chain) {
				direct = true
			}
		}
		if throughVPN {
			previous.VPN++
			previous.VPNObserved = true
		} else if direct {
			previous.Direct++
		} else {
			previous.Blocked++
		}
		if connection.Metadata.ProcessPath == "" {
			previous.Unknown++
		}
		for i, path := range paths {
			if configuredPathMatches(path, connection.Metadata.ProcessPath) {
				if throughVPN {
					previous.Apps[i].VPN++
				} else if direct {
					previous.Apps[i].Direct++
				}
			}
		}
	}
	return previous
}

// Names are generated by makeTransparentConfig, never taken from subscriptions.
func isDirectChain(chain string) bool {
	if chain == "DIRECT" || chain == "OriginalNetwork" {
		return true
	}
	if !strings.HasPrefix(chain, "Local") {
		return false
	}
	index, err := strconv.Atoi(strings.TrimPrefix(chain, "Local"))
	return err == nil && index >= 0 && chain == "Local"+strconv.Itoa(index)
}

func (c *controlFiles) refreshConnections(client *http.Client, port uint16) error {
	connections, err := coreSnapshot(client, port, c.request.Token)
	if err != nil {
		return err
	}
	c.snapshot = summarizeConnections(connections, c.request.AppPaths, c.snapshot)
	c.write("ready")
	return nil
}
func (c *controlFiles) write(state string) {
	c.snapshot.State = state
	c.snapshot.UpdatedAt = time.Now().UnixMilli()
	data, err := json.Marshal(c.snapshot)
	if err != nil {
		return
	}
	_, _ = c.status.WriteAt(data, 0)
	_ = c.status.Truncate(int64(len(data)))
}
func readRouteSnapshot(path string) (routeSnapshot, error) {
	var snapshot routeSnapshot
	file, err := os.Open(path)
	if err != nil {
		return snapshot, err
	}
	defer file.Close()
	err = json.NewDecoder(io.LimitReader(file, 1<<20)).Decode(&snapshot)
	return snapshot, err
}
